RestaurantApp/Areas/discount/Controllers/DiscountController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Newtonsoft.Json;
using RestaurantApp.Areas.admin.Controllers;
using System.Text;
using ViewModels.Models;

namespace RestaurantApp.Areas.discount.Controllers
{
    public class DiscountController : Controller
    {
        private readonly ILogger<DiscountController> _logger;
        private readonly HttpClient _client;
        private readonly IConfiguration _configuration;
        Uri baseAddress = new Uri("http://localhost:7189/api");

        public DiscountController(ILogger<DiscountController> logger, IConfiguration configuration)
        {
            _logger = logger;
            _configuration = configuration;
            _client = new HttpClient();
            _client.BaseAddress = baseAddress;

        }
        [HttpGet]
        public IActionResult Discount()
        {
            DiscountVm model = new DiscountVm();
            HttpResponseMessage response = _client.GetAsync(_client.BaseAddress + "/Discounts/Discounts").Result;

            if (response.IsSuccessStatusCode)
            {
                var rolesJson = response.Content.ReadAsStringAsync().Result;
                model.discount = JsonConvert.DeserializeObject<List<SelectListItem>>(rolesJson);
            }
            return View(model);
        }

        [HttpPost]
        public IActionResult AddDiscount(DiscountVm model)
        {
            //PostUserRegisterVm user = new PostUserRegisterVm
            //{
            //    name = model.name,
            //    //companyId = model.companyId,
            //    roleId = model.roleId,
            //    email = model.email,
            //    contact = model.contact,
            //    userCode = model.userCode,
            //    password = model.password
            //};
            try
            {
                string serializedData = JsonConvert.SerializeObject(model);
                StringContent stringContent = new StringContent(serializedData, Encoding.UTF8, "application/json");
                HttpResponseMessage response = _client.PostAsync(_client.BaseAddress + "/Discounts/AddDiscount", stringContent).Result;

            }
            catch (HttpRequestException ex)
            {
                ViewData["ErrorMessage"] = "Error: " + ex.Message;
                return View("Index");
            }
            catch (Exception ex)
            {
                ViewData["ErrorMessage"] = "Error: " + ex.Message;
                return View("Index");
            }
            TempData["success"] = "Logged in done succesfully";
            return RedirectToAction("AllDiscount");
        }


        [HttpGet]
        public IActionResult AllDiscount() //rendering the list of users in UI
        {
            //  List<ProductInfo> model = new List<ProductInfo>();
            DiscountVm model = new DiscountVm();
            HttpResponseMessage response = _client.GetAsync(_client.BaseAddress + "/Discounts/AllDiscountList").Result;
            if (response.IsSuccessStatusCode)
            {
                var userJson = response.Content.ReadAsStringAsync().Result;
                model.allDIscount = JsonConvert.DeserializeObject<List<AllDiscount>>(userJson);
            }

            return View(model);
            //return View(promodel);

        }

        public IActionResult DeleteDiscountById(int id)
        {
            try
            {

                HttpResponseMessage response = _client.GetAsync(_client.BaseAddress + "/Discounts/DeleteDiscountById/" + id).Result;

            }
            catch (HttpRequestException ex)
            {
                ViewData["ErrorMessage"] = "Error: " + ex.Message;
                return View("AllRoles");
            }
            catch (Exception ex)
            {
                ViewData["ErrorMessage"] = "Error: " + ex.Message;
                return View("AllRoles");
            }
            TempData["success"] = "Logged in done succesfully";
            return RedirectToAction("AllDiscount");
        }
    }
}

RestaurantApp/Areas/product/Controllers/ProductController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Newtonsoft.Json;
using System.Text;
using ViewModels.Models;

namespace RestaurantApp.Areas.product.Controllers
{
    public class ProductController : Controller
    {
        private readonly ILogger<ProductController> _logger;
        private readonly HttpClient _client;
        private readonly IConfiguration _configuration;
        Uri baseAddress = new Uri("http://localhost:7189/api");

        public ProductController(ILogger<ProductController> logger, IConfiguration configuration)
        {
            _logger = logger;
            _configuration = configuration;
            _client = new HttpClient();
            _client.BaseAddress = baseAddress;
        }
        #region
        /*  [HttpGet]
          public IActionResult ProductForm()
          {
              ProductAddVm model = new ProductAddVm();
              HttpResponseMessage response = _client.GetAsync(_client.BaseAddress + "/Product/ProductAdd").Result;

              if (response.IsSuccessStatusCode)
              {
                  var categoryJson = response.Content.ReadAsStringAsync().Result;
                  model.Categories = JsonConvert.DeserializeObject<List<SelectListItem>>(categoryJson);
              }
              return View(model);
          }*/
        #endregion
        [HttpGet]
        public IActionResult AllProducts() //rendering the list of users in UI
        {
            ProductInfoEditVm promodel = new ProductInfoEditVm();
            ProductAddVm addVm= new ProductAddVm();
            promodel.productadd = new ProductAddVm();
            HttpResponseMessage response = _client.GetAsync(_client.BaseAddress + "/Product/AllProductInfo").Result;
            if (response.IsSuccessStatusCode)
            {
                var userJson = response.Content.ReadAsStringAsync().Result;
                promodel.products = JsonConvert.DeserializeObject<List<ProductInfo>>(userJson);
            }
            HttpResponseMessage response1 = _client.GetAsync(_client.BaseAddress + "/Product/ProductAdd").Result;
            if (response1.IsSuccessStatusCode)
            {
                var categoryJson = response1.Content.ReadAsStringAsync().Result;
                promodel.productadd.Categories = JsonConvert.DeserializeObject<List<SelectListItem>>(categoryJson);
            }
            var tuple = new Tuple<ProductAddVm, ProductInfoEditVm>(addVm,promodel);
            return View(tuple);
            //return View(promodel);

        }
        [HttpPost]
        public IActionResult ProductAdd([Bind(Prefix = "Item1")] ProductAddVm model)//Adding users post method for UserRegister
        {
            var FileName = "";
            using (var ms = new MemoryStream())
            {
                model.image.CopyToAsync(ms);
                var imageBytes = ms.ToArray();
                var base64String = Convert.ToBase64String(imageBytes);
                FileName = "data:image/png;base64," + base64String;
            }
            PostProductAddVm user = new PostProductAddVm
            { 
              Productname= model.Productname,
              categoryId=model.categoryId,
              unitprice=model.unitprice,
              units=model.units,
              imageSrc=FileName,
            };
            try
            {
                string serializedData = JsonConvert.SerializeObject(user);
                StringContent stringContent = new StringContent(serializedData, Encoding.UTF8, "application/json");
                HttpResponseMessage response = _client.PostAsync(_client.BaseAddress + "/Product/AddProduct", stringContent).Result;
            }
            catch (HttpRequestException ex)
            {
                ViewData["ErrorMessage"] = "Error: " + ex.Message;
                return View("Index");
            }
            catch (Exception ex)
            {
                ViewData["ErrorMessage"] = "Error: " + ex.Message;
                return View("Index");
            }
            TempData["success"] = "Product Added Scuccesfully";
            return RedirectToAction("AllProducts");
        }
        [HttpGet]
        public IActionResult GetProductById(int id)
        {
            ProductEditVm model = new ProductEditVm();
            HttpResponseMessage response = _client.GetAsync(_client.BaseAddress + "/Product/GetProductById/" + id).Result;
            if (response.IsSuccessStatusCode)
            {
                var userJson = response.Content.ReadAsStringAsync().Result;
                model = JsonConvert.DeserializeObject<ProductEditVm>(userJson);
            }
            return View("ProductEditPage", model);
        }
        [HttpPost]
        public IActionResult GetProductById(ProductEditVm model)
        {
            var FileName = "";
            using (var ms = new MemoryStream())
            {
                model.image.CopyToAsync(ms);
                var imageBytes = ms.ToArray();
                var base64String = Convert.ToBase64String(imageBytes);
                FileName = "data:image/png;base64,"+ base64String;
            }
            PostProductEditVm product = new PostProductEditVm
            {
                productid = model.productid,
                productname = model.productname,
                unit = model.unit,
                unitprice = model.unitprice,
                categoryid = model.categoryid,
                isactive = model.isactive,
                imageSrc = FileName,
            };
            try
            {
                string serializedData = JsonConvert.SerializeObject(product);
                StringContent stringContent = new StringContent(serializedData, Encoding.UTF8, "application/json");
                HttpResponseMessage response = _client.PutAsync(_client.BaseAddress + "/Product/EditProduct", stringContent).Result;

            }
            catch (HttpRequestException ex)
            {
                ViewData["ErrorMessage"] = "Error: " + ex.Message;
                return View("Index");
            }
            catch (Exception ex)
            {
                ViewData["ErrorMessage"] = "Error: " + ex.Message;
                return View("Index");
            }
            TempData["success"] = "Product Edited Scuccesfully";
            return RedirectToAction("AllProducts");
        }
      
        public IActionResult DeleteProductById(int id)
        {
            try
            {
                HttpResponseMessage response = _client.DeleteAsync(_client.BaseAddress + "/Product/DeleteProductById/" + id).Result;
            }
            catch (HttpRequestException ex)
            {
                ViewData["ErrorMessage"] = "Error: " + ex.Message;
                return View("Index");
            }
            catch (Exception ex)
            {
                ViewData["ErrorMessage"] = "Error: " + ex.Message;
                return View("Index");
            }
            TempData["success"] = "Product Deleted Scuccesfully";
            return RedirectToAction("AllProducts");
        }

    }
}

RestaurantApp/Areas/role/Controllers/RoleController.cs
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using RestaurantApp.Models;
using System.Configuration;
using System.Diagnostics;
using System.Security.Claims;
using ViewModels.Models;
using System.Text;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.Data.SqlClient;
using System.Net.Mail;
using System.Net;
using Azure;
using Microsoft.EntityFrameworkCore.Metadata.Internal;

namespace RestaurantApp.Areas.role.Controllers
{
    public class RoleController : Controller
    {
        private readonly ILogger<RoleController> _logger;
        private readonly HttpClient _client;
        private readonly IConfiguration _configuration;
        Uri baseAddress = new Uri("http://localhost:7189/api");

        public RoleController(ILogger<RoleController> logger, IConfiguration configuration)
        {
            _logger = logger;
            _configuration = configuration;
            _client = new HttpClient();
            _client.BaseAddress = baseAddress;

        }

        [HttpGet]
        public IActionResult RoleRegister()
        {
            return View();
        }

        [HttpPost]
        public IActionResult RoleRegister(RoleRegisterVm model)
        {
            try
            {
                string serializedData = JsonConvert.SerializeObject(model);
                StringContent stringContent = new StringContent(serializedData, Encoding.UTF8, "application/json");
                HttpResponseMessage response = _client.PostAsync(_client.BaseAddress + "/Role/AddRole", stringContent).Result;

            }
            catch (HttpRequestException ex)
            {
                ViewData["ErrorMessage"] = "Error: " + ex.Message;
                return View("AllRoles");
            }
            catch (Exception ex)
            {
                ViewData["ErrorMessage"] = "Error: " + ex.Message;
                return View("AllRoles");
            }
            TempData["success"] = "Logged in done succesfully";
            return RedirectToAction("AllRoles");
        }


        [HttpGet]
        public IActionResult AllRoles() //rendering the list of users in UI
        {
            //  List<ProductInfo> model = new List<ProductInfo>();
            RoleRegisterVm model = new RoleRegisterVm();
            HttpResponseMessage response = _client.GetAsync(_client.BaseAddress + "/Role/AllRoles").Result;
            if (response.IsSuccessStatusCode)
            {
                var userJson = response.Content.ReadAsStringAsync().Result;
                model.roles = JsonConvert.DeserializeObject<List<RoleInfoVm>>(userJson);
            }

            return View(model);
            //return View(promodel);

        }


        [HttpGet]
        public IActionResult GetRoleById(int id) //rendering the list of users in UI
        {
            RoleById model = new RoleById();
            try
            {
                HttpResponseMessage response = _client.GetAsync(_client.BaseAddress + "/Role/RoleById/" + id).Result;

                if (response.IsSuccessStatusCode)
                {
                   
                    var userJson = response.Content.ReadAsStringAsync().Result;
                    model = JsonConvert.DeserializeObject<RoleById>(userJson);
                }
            }
            catch (HttpRequestException ex)
            {
                ViewData["ErrorMessage"] = "Error: " + ex.Message;
                return View("Index");
            }
            catch (Exception ex)
            {
                ViewData["ErrorMessage"] = "Error: " + ex.Message;
                return View("Index");
            }
            TempData["success"] = "Product Edited Scuccesfully";
            return Json(model);
        }

        [HttpPost]
        public IActionResult RoleEdit(RoleRegisterVm model)
        {
            try
            {
                string serializedData = JsonConvert.SerializeObject(model.rolebyid);
                StringContent stringContent = new StringContent(serializedData, Encoding.UTF8, "application/json");
                HttpResponseMessage response = _client.PostAsync(_client.BaseAddress + "/Role/EditRole", stringContent).Result;

            }
            catch (HttpRequestException ex)
            {
                ViewData["ErrorMessage"] = "Error: " + ex.Message;
                return View("AllRoles");
            }
            catch (Exception ex)
            {
                ViewData["ErrorMessage"] = "Error: " + ex.Message;
                return View("AllRoles");
            }
            TempData["success"] = "Logged in done succesfully";
            return RedirectToAction("AllRoles");
        }

    
        public IActionResult DeleteRoleById(int id)
        {
            try
            {
          
                HttpResponseMessage response = _client.GetAsync(_client.BaseAddress + "/Role/DeleteRoleById/" + id).Result;

            }
            catch (HttpRequestException ex)
            {
                ViewData["ErrorMessage"] = "Error: " + ex.Message;
                return View("AllRoles");
            }
            catch (Exception ex)
            {
                ViewData["ErrorMessage"] = "Error: " + ex.Message;
                return View("AllRoles");
            }
            TempData["success"] = "Logged in done succesfully";
            return RedirectToAction("AllRoles");
        }
    }
}

RestaurantApp/Areas/admin/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - RestaurantApp</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link href="~/css/DatatableCss/jquery.dataTables.css" rel="stylesheet" />
    <link href="~/css/DatatableCss/jquery.dataTables.min.css" rel="stylesheet />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.5/font/bootstrap-icons.css">
    <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/css/toastr.min.css" />
    <link rel="stylesheet" href="~/RestaurantApp.styles.css" asp-append-version="true" />
    @* <link rel="stylesheet" href="https://cdn.datatables.net/1.13.4/css/jquery.dataTables.css" />*@
    <link href="~/css/respos.css" rel="stylesheet" />
    <script src="~/lib/jquery/dist/jquery.min.js"></script>



</head>
<body>
    <div class="container-fluid">
        <main role="main" class="pb-3">

            <div id="mySidebar" class="sidebar">
                <div class="toggle-nav" style="">
                    <img src="~/images/restaurant2.jpg" style="opacity: 0.2;width: 100%;object-fit: cover;" alt="">
                    <p style="" class="m-0 aramex-title">
                        Food Zone
                    </p>
                    <a href="javascript:void(0)" style="padding: 0px;" class="closebtn" onclick="closeNav()">&times;</a>
                </div>


                <p id="drp" class="drpdes">
                    <a style="    margin-left: 15px;font-size:medium" asp-action="ServicesPage" asp-area="services" asp-controller="Service">ServicesPage</a>
                </p>
                <div id="drp" class="drp">
                    <p style=" margin-left: 15px;font-size:medium"> Master <span style="margin-left: 150px;"><i class="bi bi-chevron-down arrow"></i></span></p>
                </div>


                <div class="drpclass d-none" style=" background-color: #ffe599;"
                    <hr>
                    <div style=" background-color: #ffe599;">
                        <a type="button" asp-area="admin" asp-action="AllUsers" asp-controller="Home" type="button" class="pages" style="font-weight: 500;color: black;margin-left: 10px;">
                            <div style="">All Users</div>
                        </a>
                    </div>
                    <hr>
                    <div class="" style=" background-color: #ffe599;">
                        <a type="button" asp-area="category" asp-action="AllCategories" asp-controller="Category" type="button" class="pages" style="font-weight: 500;color: black;margin-left: 10px;">
                            <div style="">All Caegories</div>
                        </a>
                    </div>
                    <hr>
                    <div class="" style=" background-color: #ffe599;">
                        <a type="button" asp-area="product" asp-action="AllProducts" asp-controller="Product" type="button" class="layout-links" style="font-weight: 500;color: black;margin-left: 10px;">
                            <div style="">All Products</div>
                        </a>
                    </div>
                    <hr>
                     <div class="" style=" background-color: #ffe599;">
                        <a type="button" asp-area="role" asp-action="AllRoles" asp-controller="Role" type="button" class="pages"  style="font-weight: 500;color: black;margin-left: 10px;">
                            <div style="">Roles</div>
                        </a>
                    </div>
                    <hr>
                   
                    <div class="" style=" background-color: #ffe599;">
                        <a type="button" asp-area="discount" asp-action="AllDiscount" asp-controller="Discount" type="button" class="pages" style="font-weight: 500;color: black;margin-left: 10px;">
                            <div style="">Discount Master</div>
                        </a>
                    </div>
                    <hr>
                </div>

                <p id="drp" class="drpdes">
                    <a style="text-decoration:none;color:red ; font-size:medium;margin-left:15px" asp-area="orders" asp-action="OrdersDetails" asp-controller="Orders">Order Details</a>
                </p>

            </div>
            <!-- toggle ends -->
            <div id="main" style="z-index: 1;">
                <button class="openbtn position-absolute" onclick="openNav()">
                    <img src="~/images/burger.png" alt="" class="burgerImg">
                </button>
            </div>


            <!-- toggle 2  -->

            <div id="mySidebar2" class="sidebar2">
                <div class="toggle-nav" style="">
                    <img src="~/images/restaurant2.jpg" style="opacity: 0.2;width: 100%;object-fit: cover;" alt="">
                    <p style="" class="m-0 aramex-title">
                        Food Zone
                    </p>
                    <a href="javascript:void(0)" style="padding: 0px;" class="closebtn" onclick="closeNav()">&times;</a>
                </div>


                <p id="drp" class="drpdes">
                    <a style="    margin-left: 15px;font-size:medium" asp-action="ServicesPage" asp-area="services" asp-controller="Service">ServicesPage</a>
                </p>
                <div id="drp" class="drp">
                    <p style=" margin-left: 15px;font-size:medium"> Master <span style="margin-left: 150px;"><i class="bi bi-chevron-down arrow"></i></span></p>
                </div>


                <div class="drpclass d-none" style=" background-color: #ffe599;"
                    <hr>
                    <div style=" background-color: #ffe599;">
                        <a type="button" asp-area="admin" asp-action="AllUsers" asp-controller="Home" type="button" class="pages" style="font-weight: 500;color: black;margin-left: 10px;">
                            <div style="">All Users</div>
                        </a>
                    </div>
                    <hr>
                    <div class="" style=" background-color: #ffe599;">
                        <a type="button" asp-area="category" asp-action="AllCategories" asp-controller="Category" type="button" class="pages" style="font-weight: 500;color: black;margin-left: 10px;">
                            <div style="">All Caegories</div>
                        </a>
                    </div>
                    <hr>
                    <div class="" style=" background-color: #ffe599;">
                        <a type="button" asp-area="product" asp-action="AllProducts" asp-controller="Product" type="button" class="layout-links" style="font-weight: 500;color: black;margin-left: 10px;">
                            <div style="">All Products</div>
                        </a>
                    </div>
                    <hr>
                     <div class="" style=" background-color: #ffe599;">
                        <a type="button" asp-area="role" asp-action="AllRoles" asp-controller="Role" type="button" class="pages"  style="font-weight: 500;color: black;margin-left: 10px;">
                            <div style="">Roles</div>
                        </a>
                    </div>
                    <hr>

                    <div class="" style=" background-color: #ffe599;">
                        <a type="button" asp-area="discount" asp-action="AllDiscount" asp-controller="Discount" type="button" class="pages" style="font-weight: 500;color: black;margin-left: 10px;">
                            <div style="">Discount Master</div>
                        </a>
                    </div>
                    <hr>
                </div>

                <p id="drp" class="drpdes">
                    <a style="text-decoration:none;color:red ; font-size:medium;margin-left:15px" asp-area="orders" asp-action="OrdersDetails" asp-controller="Orders">Order Details</a>
                </p>


            </div>



           


            <div id="main2" style="z-index: 1;">
                <button class="openbtn2 position-absolute" onclick="openNav2()">
                    <img class="burgerImg"
                         src="~/images/burger.png" alt="">
                </button>
            </div>
            <!-- toggle 2 ends -->





            <div class="container-fluid row secondNav position-relative"
                 style="display: flex;height: 80px;justify-content: center;margin: 0px;object-fit: contain;  border-bottom: solid 2px;border-bottom-color: black; ">
                <img src="~/images/restaurant2.jpg"
                     style="height: 80px; width: 100%;object-fit: cover;opacity: 0.2;position: relative;" alt="">
                <div class="resTitle">
                    <img style="height:35px;width:35px" src="~/images/icon.png" /><p class="resp"> Restaurant POS</p>
                </div>
                <div class="dropdown text-end" style="position: absolute;right: 10px;top: 15px;background-color: #ffe599;border: solid grey 1px;border-radius: 11px;box-shadow: 4px 5px 5px #6c757d;">
                   
                    <div class="profile mt-1" style="display: flex;">
                        <a href="#" class="d-block link-dark text-decoration-none dropdown-toggle" data-bs-toggle="dropdown"
                           aria-expanded="false">
                            <img src="~/images/pizza.png" alt="mdo" class="rounded-circle profileImg"><span class="profileSpan">
                                Evan
                                Donohue
                            </span>
                        </a>
                        <ul class="dropdown-menu text-small" style="background-color: #ffe599">


                            <li><a class="dropdown-item" asp-action="Index" asp-controller="Home">Sign out</a></li>
                            <li><a class="dropdown-item" asp-action="" asp-controller="">Profile</a></li>

                        </ul>

                    </div>
                </div>
            </div>

            <div class="container-fluid" style=" height: 700px;">

                <div class="row page" style="">
                    @RenderBody()
                </div>



            </div>
        </main>
    </div>
 
    <script>


    </script>

    <script src="~/Datatable/jquery.dataTables.js"></script>
    <script src="~/Datatable/jquery.dataTables.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="~/lib/jquery-validation/dist/jquery.validate.min.js"></script>
    <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.min.js"></script>

    <script src="~/js/layout.js"></script>
    <script src="~/js/animation.js"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>